version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Installing CMAKE
          command: sudo apt install -y cmake libboost-python-dev libboost-numpy-dev libboost-all-dev
      - run:
          name: Create Virtual Environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
      - run:
          name: Creating Build Files
          command: sudo cmake -H. -Bbuild -DENABLE_TESTING=1 -DGENERATE_PYTHON_BINDINGS=1
      - run:
          name: Compiling
          command: sudo cmake --build build -j2
      - run:
          name: Installing
          command: sudo cmake --build build --target install -j2
      - run:
          name: PIP installing
          command: sudo pip install .
      - run:
          name: Testing
          command: cd build && make test
