version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Installing CMAKE
          command: |
            sudo apt update -y
            sudo apt install -y cmake libboost-python-dev libboost-numpy-dev libboost-all-dev python3-numpy
      - run:
          name: Create Virtual Environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
      - run:
          name: Creating Build Files
          command: cmake -H. -Bbuild -DENABLE_TESTING=1 -DGENERATE_PYTHON_BINDINGS=1
      - run:
          name: Compiling
          command: cmake --build build -j2
      - run:
          command: ls /usr/local/lib64/python3.10/site-packages
      - run:
          command: ls /usr/local/lib/python3.10/site-packages
      - run:
          command: ls /usr/local/lib64
      - run:
          name: Installing
          command: sudo cmake --build build --target install -j2
      - run:
          name: PIP installing
          command: |
            pip install numpy
            pip install .
      - run:
          name: Testing
          command: cd build && make test
