name: Build

on:
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # only publish on a release (tag)
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-12,ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*  # build for 3.8 and higher
          CIBW_ARCHS_MACOS: x86_64 arm64 # explicitly also build for mac arm processors

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/*.whl

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels
    environment:
      name: release
      url: https://pypi.org/p/multineat
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
