name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: dependencies
        run: sudo apt install -y libboost-all-dev
      - name: cmake
        run: cmake -B build -DENABLE_TESTING=ON
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest
      - name: install
        run: sudo cmake --build build --target install
