name: Python Bindings

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install -y libcereal-dev libboost-all-dev python3-pybind11 pybind11-dev
    - name: pip install
      run: pip install .
    - name: test import
      run: cd tests/python && ./test_import.py
    - name: test raw genome
      run: cd tests/python && ./test_raw_genome.py
    - name: test xor
      run: cd tests/python && ./test_xor.py
